apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
data:
  promtail.conf: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://1.15.240.212:3100/loki/api/v1/push

    scrape_configs:
    - job_name: nginx-access
      static_configs:
        - targets:
            - localhost
          labels:
            job: nginx-access-log
            cluster: dev
            host: ${NODE_NAME:unknown}
            pod_namespace: ${POD_NAMESPACE:unknown}
            pod_name: ${POD_NAME:unknown}
            service: ${SERVICE_NAME:unknown}
            __path__: /var/log/nginx/access.log
